/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourSlugRouteImport } from './routes/tour.$slug'
import { Route as LiveCodeRouteImport } from './routes/live.$code'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardLiveRouteImport } from './routes/_authenticated/dashboard.live'
import { Route as AuthenticatedDashboardEditorSlugRouteImport } from './routes/_authenticated/dashboard.editor.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCodeRoute = LiveCodeRouteImport.update({
  id: '/live/$code',
  path: '/live/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardLiveRoute =
  AuthenticatedDashboardLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEditorSlugRoute =
  AuthenticatedDashboardEditorSlugRouteImport.update({
    id: '/editor/$slug',
    path: '/editor/$slug',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/live/$code': typeof LiveCodeRoute
  '/tour/$slug': typeof TourSlugRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/editor/$slug': typeof AuthenticatedDashboardEditorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/live/$code': typeof LiveCodeRoute
  '/tour/$slug': typeof TourSlugRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/editor/$slug': typeof AuthenticatedDashboardEditorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/live/$code': typeof LiveCodeRoute
  '/tour/$slug': typeof TourSlugRoute
  '/_authenticated/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/_authenticated/dashboard/editor/$slug': typeof AuthenticatedDashboardEditorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/live/$code'
    | '/tour/$slug'
    | '/dashboard/live'
    | '/dashboard/editor/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/live/$code'
    | '/tour/$slug'
    | '/dashboard/live'
    | '/dashboard/editor/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/live/$code'
    | '/tour/$slug'
    | '/_authenticated/dashboard/live'
    | '/_authenticated/dashboard/editor/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LiveCodeRoute: typeof LiveCodeRoute
  TourSlugRoute: typeof TourSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$code': {
      id: '/live/$code'
      path: '/live/$code'
      fullPath: '/live/$code'
      preLoaderRoute: typeof LiveCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/live': {
      id: '/_authenticated/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof AuthenticatedDashboardLiveRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/editor/$slug': {
      id: '/_authenticated/dashboard/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/dashboard/editor/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardEditorSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLiveRoute: typeof AuthenticatedDashboardLiveRoute
  AuthenticatedDashboardEditorSlugRoute: typeof AuthenticatedDashboardEditorSlugRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLiveRoute: AuthenticatedDashboardLiveRoute,
    AuthenticatedDashboardEditorSlugRoute:
      AuthenticatedDashboardEditorSlugRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LiveCodeRoute: LiveCodeRoute,
  TourSlugRoute: TourSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
