/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourSlugRouteImport } from './routes/tour.$slug'
import { Route as LiveCodeRouteImport } from './routes/live.$code'
import { Route as BrokerIdRouteImport } from './routes/broker.$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardPerfilRouteImport } from './routes/_authenticated/dashboard.perfil'
import { Route as AuthenticatedDashboardNuevoRouteImport } from './routes/_authenticated/dashboard.nuevo'
import { Route as AuthenticatedDashboardLiveRouteImport } from './routes/_authenticated/dashboard.live'
import { Route as AuthenticatedDashboardInmueblesRouteImport } from './routes/_authenticated/dashboard.inmuebles'
import { Route as AuthenticatedDashboardFacturacionRouteImport } from './routes/_authenticated/dashboard.facturacion'
import { Route as AuthenticatedDashboardEditorSlugRouteImport } from './routes/_authenticated/dashboard.editor.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCodeRoute = LiveCodeRouteImport.update({
  id: '/live/$code',
  path: '/live/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerIdRoute = BrokerIdRouteImport.update({
  id: '/broker/$id',
  path: '/broker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardPerfilRoute =
  AuthenticatedDashboardPerfilRouteImport.update({
    id: '/dashboard/perfil',
    path: '/dashboard/perfil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardNuevoRoute =
  AuthenticatedDashboardNuevoRouteImport.update({
    id: '/dashboard/nuevo',
    path: '/dashboard/nuevo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardLiveRoute =
  AuthenticatedDashboardLiveRouteImport.update({
    id: '/dashboard/live',
    path: '/dashboard/live',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardInmueblesRoute =
  AuthenticatedDashboardInmueblesRouteImport.update({
    id: '/dashboard/inmuebles',
    path: '/dashboard/inmuebles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFacturacionRoute =
  AuthenticatedDashboardFacturacionRouteImport.update({
    id: '/dashboard/facturacion',
    path: '/dashboard/facturacion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEditorSlugRoute =
  AuthenticatedDashboardEditorSlugRouteImport.update({
    id: '/dashboard/editor/$slug',
    path: '/dashboard/editor/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/broker/$id': typeof BrokerIdRoute
  '/live/$code': typeof LiveCodeRoute
  '/tour/$slug': typeof TourSlugRoute
  '/dashboard/facturacion': typeof AuthenticatedDashboardFacturacionRoute
  '/dashboard/inmuebles': typeof AuthenticatedDashboardInmueblesRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/nuevo': typeof AuthenticatedDashboardNuevoRoute
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/editor/$slug': typeof AuthenticatedDashboardEditorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/broker/$id': typeof BrokerIdRoute
  '/live/$code': typeof LiveCodeRoute
  '/tour/$slug': typeof TourSlugRoute
  '/dashboard/facturacion': typeof AuthenticatedDashboardFacturacionRoute
  '/dashboard/inmuebles': typeof AuthenticatedDashboardInmueblesRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/nuevo': typeof AuthenticatedDashboardNuevoRoute
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/editor/$slug': typeof AuthenticatedDashboardEditorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/broker/$id': typeof BrokerIdRoute
  '/live/$code': typeof LiveCodeRoute
  '/tour/$slug': typeof TourSlugRoute
  '/_authenticated/dashboard/facturacion': typeof AuthenticatedDashboardFacturacionRoute
  '/_authenticated/dashboard/inmuebles': typeof AuthenticatedDashboardInmueblesRoute
  '/_authenticated/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/_authenticated/dashboard/nuevo': typeof AuthenticatedDashboardNuevoRoute
  '/_authenticated/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/editor/$slug': typeof AuthenticatedDashboardEditorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/broker/$id'
    | '/live/$code'
    | '/tour/$slug'
    | '/dashboard/facturacion'
    | '/dashboard/inmuebles'
    | '/dashboard/live'
    | '/dashboard/nuevo'
    | '/dashboard/perfil'
    | '/dashboard/'
    | '/dashboard/editor/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/broker/$id'
    | '/live/$code'
    | '/tour/$slug'
    | '/dashboard/facturacion'
    | '/dashboard/inmuebles'
    | '/dashboard/live'
    | '/dashboard/nuevo'
    | '/dashboard/perfil'
    | '/dashboard'
    | '/dashboard/editor/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/broker/$id'
    | '/live/$code'
    | '/tour/$slug'
    | '/_authenticated/dashboard/facturacion'
    | '/_authenticated/dashboard/inmuebles'
    | '/_authenticated/dashboard/live'
    | '/_authenticated/dashboard/nuevo'
    | '/_authenticated/dashboard/perfil'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/editor/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  BrokerIdRoute: typeof BrokerIdRoute
  LiveCodeRoute: typeof LiveCodeRoute
  TourSlugRoute: typeof TourSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$code': {
      id: '/live/$code'
      path: '/live/$code'
      fullPath: '/live/$code'
      preLoaderRoute: typeof LiveCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/$id': {
      id: '/broker/$id'
      path: '/broker/$id'
      fullPath: '/broker/$id'
      preLoaderRoute: typeof BrokerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/perfil': {
      id: '/_authenticated/dashboard/perfil'
      path: '/dashboard/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof AuthenticatedDashboardPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/nuevo': {
      id: '/_authenticated/dashboard/nuevo'
      path: '/dashboard/nuevo'
      fullPath: '/dashboard/nuevo'
      preLoaderRoute: typeof AuthenticatedDashboardNuevoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/live': {
      id: '/_authenticated/dashboard/live'
      path: '/dashboard/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof AuthenticatedDashboardLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/inmuebles': {
      id: '/_authenticated/dashboard/inmuebles'
      path: '/dashboard/inmuebles'
      fullPath: '/dashboard/inmuebles'
      preLoaderRoute: typeof AuthenticatedDashboardInmueblesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/facturacion': {
      id: '/_authenticated/dashboard/facturacion'
      path: '/dashboard/facturacion'
      fullPath: '/dashboard/facturacion'
      preLoaderRoute: typeof AuthenticatedDashboardFacturacionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/editor/$slug': {
      id: '/_authenticated/dashboard/editor/$slug'
      path: '/dashboard/editor/$slug'
      fullPath: '/dashboard/editor/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardEditorSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardFacturacionRoute: typeof AuthenticatedDashboardFacturacionRoute
  AuthenticatedDashboardInmueblesRoute: typeof AuthenticatedDashboardInmueblesRoute
  AuthenticatedDashboardLiveRoute: typeof AuthenticatedDashboardLiveRoute
  AuthenticatedDashboardNuevoRoute: typeof AuthenticatedDashboardNuevoRoute
  AuthenticatedDashboardPerfilRoute: typeof AuthenticatedDashboardPerfilRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardEditorSlugRoute: typeof AuthenticatedDashboardEditorSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardFacturacionRoute:
    AuthenticatedDashboardFacturacionRoute,
  AuthenticatedDashboardInmueblesRoute: AuthenticatedDashboardInmueblesRoute,
  AuthenticatedDashboardLiveRoute: AuthenticatedDashboardLiveRoute,
  AuthenticatedDashboardNuevoRoute: AuthenticatedDashboardNuevoRoute,
  AuthenticatedDashboardPerfilRoute: AuthenticatedDashboardPerfilRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardEditorSlugRoute: AuthenticatedDashboardEditorSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  BrokerIdRoute: BrokerIdRoute,
  LiveCodeRoute: LiveCodeRoute,
  TourSlugRoute: TourSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
